ceph_origin: repository
ceph_repository: community
ceph_stable_release: luminous
monitor_interface: 130.127.133.132
public_network: 130.127.132.0/22
cluster_network: "{{public_network}}"
ceph_conf_overrides:
    osd:
        osd scrub during recovery: false
docker: true
ceph_docker_image: "ceph/daemon"
ceph_docker_image_tag: latest
ceph_docker_registry: docker.io
containerized_deployment: true
devices:
  - '/dev/sda'
  - '/dev/sdb'



  --------

crush_location: true
osd_crush_location: "\"root={{ ceph_crush_root }} rack={{ ceph_crush_rack }} host={{ ansible_hostname }}\""
osd_objectstore: bluestore
osd_scenario: non-collocated
devices:
- /dev/sda
- /dev/sdb