benchmarks:
- name: rados-bench
  image: mariettesouppe/rados_bench:master-ec8d33f-luminous-ubuntu-16.04-x86_64
  network_mode: host
  privilaged: true
  devices:
  - /dev/sdb
  environment:
    DEBUG: verbose
  environment_host:
    node0:
      MONITOR: true
      MON_IP: 130.127.133.166
      CEPH_PUBLIC_NETWORK: 130.127.132.0/22
    node1:
      OSD: true
      OSD_DEVICES: /dev/sdb
      MON_IP: 130.127.133.166
      CEPH_PUBLIC_NETWORK: 130.127.132.0/22
    node2:
      CLIENT: true
      MON_IP: 130.127.133.166
      CEPH_PUBLIC_NETWORK: 130.127.132.0/22