install_facter: false
benchmarks:
- name: rados-bench
  image: rados_bench:master-ec8d33f-luminous-ubuntu-16.04-x86_64
  network_mode: ceph_net
  environment_host:
    node1:
      MONITOR: true
      CEPH_NET: 175.20.0.0/16
    node2:
      OSD: true
      MONITOR_IP: 
      CEPH_NET: 175.20.0.0/16
    node3:
      CLIENT: true
      MONITOR_IP: 
      CEPH_NET: 175.20.0.0/16
  ip_host:
    node0: 
