benchmarks:
- name: rados-bench
  image: rados_bench:master-ec8d33f-luminous-ubuntu-16.04-x86_64
  network_mode: host
  environment_host:
    node1:
      MONITOR: true
      MON_IP: 128.110.153.197
      CEPH_PUBLIC_NETWORK: 128.110.153.0/100
    node2:
      OSD: true
      OSD_DEVICES: /dev/sdb
      MON_IP: 128.110.153.114
      CEPH_PUBLIC_NETWORK: 128.110.153.0/100
    node3:
      CLIENT: true
      MON_IP: 128.110.153.173
      CEPH_PUBLIC_NETWORK: 128.110.153.0/100