install_facter: false
benchmarks:
- name: rados-bench
  image: rados_bench:master-ec8d33f-luminous-ubuntu-16.04-x86_64
  network_mode: cephnet
  environment_host:
    node1:
      MONITOR: true
      MON_IP: 175.20.0.12
      CEPH_PUBLIC_NETWORK: 175.20.0.0/16
    node2:
      OSD: true
      OSD_DEVICES: /dev/sdb
      MON_IP: 175.20.0.12
      CEPH_PUBLIC_NETWORK: 175.20.0.0/16
    node3:
      CLIENT: true
      MON_IP: 175.20.0.12
      CEPH_PUBLIC_NETWORK: 175.20.0.0/16
  ip_host:
    node0: 175.20.0.12
